# =============================================================================
# SkillUp — Build, push to ECR, and deploy to EC2
#
# Prerequisites:
#   - aws-provision.ps1 has been run (scripts/aws-resources.txt exists)
#   - RDS and ElastiCache endpoints are known
#   - Docker Desktop is running
# =============================================================================

param(
    [string]$Region      = "ap-southeast-1",
    [string]$ResourceFile = "$PSScriptRoot\aws-resources.txt"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ── Load resource IDs from provisioning output ────────────────────────────────
if (-not (Test-Path $ResourceFile)) {
    Write-Error "Run aws-provision.ps1 first. Expected: $ResourceFile"
}
$res = @{}
Get-Content $ResourceFile | ForEach-Object {
    $parts = $_ -split "=", 2
    if ($parts.Count -eq 2) { $res[$parts[0].Trim()] = $parts[1].Trim() }
}
$PublicIp  = $res["EC2_PUBLIC_IP"]
$EcrUri    = $res["ECR_URI"]
$KeyFile   = $res["KEY_FILE"]
$AppName   = "skillup"

Write-Host "`n=== SkillUp Deploy to EC2 ===" -ForegroundColor Cyan
Write-Host "EC2  : $PublicIp"
Write-Host "ECR  : $EcrUri"

# ── Get live RDS + Redis endpoints ───────────────────────────────────────────
Write-Host "`n[1/5] Fetching RDS endpoint..." -ForegroundColor Yellow
$RdsHost = aws rds describe-db-instances `
    --db-instance-identifier "$AppName-postgres" `
    --query "DBInstances[0].Endpoint.Address" `
    --output text --region $Region

Write-Host "[1/5] Fetching ElastiCache endpoint..." -ForegroundColor Yellow
$RedisHost = aws elasticache describe-cache-clusters `
    --cache-cluster-id "$AppName-redis" `
    --show-cache-node-info `
    --query "CacheClusters[0].CacheNodes[0].Endpoint.Address" `
    --output text --region $Region

Write-Host "    RDS   : $RdsHost"
Write-Host "    Redis : $RedisHost"

# ── Build Docker image ────────────────────────────────────────────────────────
Write-Host "`n[2/5] Building Docker image..." -ForegroundColor Yellow
$AccountId = aws sts get-caller-identity --query Account --output text
$ImageTag  = "$EcrUri`:latest"
$BucketName = $res["S3_BUCKET"]

Push-Location "$PSScriptRoot\..\backend"
docker build -t $ImageTag .
Pop-Location
Write-Host "    Built: $ImageTag" -ForegroundColor Green

# ── Push to ECR ───────────────────────────────────────────────────────────────
Write-Host "`n[3/5] Pushing to ECR..." -ForegroundColor Yellow
aws ecr get-login-password --region $Region | docker login --username AWS --password-stdin "$AccountId.dkr.ecr.$Region.amazonaws.com"
docker push $ImageTag
Write-Host "    Pushed: $ImageTag" -ForegroundColor Green

# ── Build .env for EC2 ────────────────────────────────────────────────────────
Write-Host "`n[4/5] Generating EC2 .env file..." -ForegroundColor Yellow

$DbPassword = Read-Host -Prompt "RDS postgres password (same as provisioning)"

$EnvContent = @"
# Auto-generated by deploy-to-ec2.ps1 — do not edit by hand
SPRING_PROFILES_ACTIVE=prod
SERVER_PORT=8088

DB_USERNAME=skillup_app
DB_PASSWORD=skillup_app_pass
POSTGRES_HOST=$RdsHost
POSTGRES_PORT=5432
POSTGRES_DB=skillup_db
POSTGRES_SUPERUSER_PASSWORD=$DbPassword

REDIS_HOST=$RedisHost
REDIS_PORT=6379
REDIS_PASSWORD=skillup_redis_pass

KEYCLOAK_ENABLED=true
KEYCLOAK_BASE_URL=http://${PublicIp}:8070
KEYCLOAK_REALM=skillup
KEYCLOAK_ADMIN_USERNAME=admin
KEYCLOAK_ADMIN_PASSWORD=admin_pass
KEYCLOAK_PORTAL_CLIENT_ID=skillup-portal
KEYCLOAK_PORTAL_CLIENT_SECRET=
KEYCLOAK_ISSUER_URI=http://${PublicIp}:8070/realms/skillup
KEYCLOAK_JWK_URI=http://${PublicIp}:8070/realms/skillup/protocol/openid-connect/certs

STORAGE_ENABLED=true
STORAGE_ENDPOINT=
STORAGE_ACCESS_KEY=
STORAGE_SECRET_KEY=
STORAGE_REGION=$Region
STORAGE_BUCKET=$BucketName
STORAGE_PRESIGN_EXPIRY=15

WHATSAPP_ENABLED=false
WHATSAPP_PHONE_NUMBER_ID=
WHATSAPP_ACCESS_TOKEN=
WHATSAPP_FROM_NAME=SkillUp Tuition Centre

PORTAL_LOCAL_DEV_BYPASS=false
ECR_IMAGE=$ImageTag
"@

$EnvContent | Out-File -FilePath "$PSScriptRoot\ec2.env" -Encoding utf8
Write-Host "    Saved to scripts/ec2.env" -ForegroundColor Green

# ── Deploy to EC2 via SSH ─────────────────────────────────────────────────────
Write-Host "`n[5/5] Deploying to EC2..." -ForegroundColor Yellow

# Copy files to EC2
$SshArgs = "-i `"$KeyFile`" -o StrictHostKeyChecking=no ec2-user@$PublicIp"
$ScpBase = "scp -i `"$KeyFile`" -o StrictHostKeyChecking=no"

# Copy env file and docker-compose
Invoke-Expression "scp $SshArgs -i `"$KeyFile`" -o StrictHostKeyChecking=no `"$PSScriptRoot\ec2.env`" ec2-user@${PublicIp}:/opt/skillup/.env"
Invoke-Expression "scp $SshArgs -i `"$KeyFile`" -o StrictHostKeyChecking=no `"$PSScriptRoot\..\docker-compose.ec2.yml`" ec2-user@${PublicIp}:/opt/skillup/docker-compose.yml"
Invoke-Expression "scp $SshArgs -i `"$KeyFile`" -o StrictHostKeyChecking=no -r `"$PSScriptRoot\..\keycloak`" ec2-user@${PublicIp}:/opt/skillup/"

# Run deployment on EC2
$RemoteScript = @"
set -e
cd /opt/skillup

# Configure Docker to use ECR
aws ecr get-login-password --region $Region | docker login --username AWS --password-stdin $AccountId.dkr.ecr.$Region.amazonaws.com

# Pull latest image
docker pull $ImageTag

# Initialize MinIO bucket (S3 used instead — skip)

# Start services
docker compose --env-file .env up -d --remove-orphans

# Wait for backend to be healthy
echo 'Waiting for backend...'
for i in \$(seq 1 30); do
  if curl -sf http://localhost:8088/api/actuator/health > /dev/null 2>&1; then
    echo 'Backend healthy!'
    break
  fi
  sleep 5
done

docker compose ps
"@

$RemoteScript | ssh -i "$KeyFile" -o StrictHostKeyChecking=no "ec2-user@$PublicIp" bash

Write-Host "`n============================================================" -ForegroundColor Cyan
Write-Host " DEPLOYMENT COMPLETE" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Backend API : http://$PublicIp`:8088/api"
Write-Host "Swagger UI  : http://$PublicIp`:8088/api/swagger-ui.html  (prod: disabled)"
Write-Host "Keycloak    : http://$PublicIp`:8070"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Run the DB init script via SSH:"
Write-Host "     ssh -i $KeyFile ec2-user@$PublicIp"
Write-Host "     psql -h $RdsHost -U postgres -f /opt/skillup/scripts/01_create_db_and_user.sql"
Write-Host "  2. Update KEYCLOAK_PORTAL_CLIENT_SECRET in /opt/skillup/.env"
Write-Host "  3. Add WHATSAPP credentials when ready"
Write-Host "  4. Point a domain to $PublicIp and add HTTPS via Certbot"
