package com.skillup.student.domain;

import com.skillup.branch.domain.Branch;
import com.skillup.common.BaseEntity;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 * Core student record.
 *
 * Every student belongs to exactly one branch (their primary tuition centre).
 * Personal details, academic info, and enrollment status are managed here.
 * Class registrations live in the ClassManagement module.
 */
@Entity
@Table(name = "students")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Student extends BaseEntity {

    /**
     * Human-readable ID shown on receipts and reports.
     * Format: STU-YYYY-NNNN (e.g. STU-2026-0001).
     * Generated by StudentService using the student_id_seq PostgreSQL sequence.
     */
    @Column(name = "student_ref", nullable = false, unique = true, length = 20)
    private String studentRef;

    // ── Personal details ──────────────────────────────────────────────────────

    @Column(name = "full_name", nullable = false, length = 150)
    private String fullName;

    @Column(name = "preferred_name", length = 80)
    private String preferredName;

    @Column(name = "ic_number", length = 20)
    private String icNumber;

    @Column(name = "date_of_birth")
    private LocalDate dateOfBirth;

    @Enumerated(EnumType.STRING)
    @Column(name = "gender", nullable = false, length = 10)
    @Builder.Default
    private Gender gender = Gender.UNSPECIFIED;

    @Column(name = "nationality", length = 60)
    @Builder.Default
    private String nationality = "Malaysian";

    @Column(name = "photo_url", length = 500)
    private String photoUrl;

    // ── Academic details ──────────────────────────────────────────────────────

    @Column(name = "school_name", length = 150)
    private String schoolName;

    @Column(name = "current_grade", length = 30)
    private String currentGrade;

    // ── Enrollment ────────────────────────────────────────────────────────────

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    @Builder.Default
    private StudentStatus status = StudentStatus.ACTIVE;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "branch_id", nullable = false)
    private Branch branch;

    @Column(name = "enrolled_date", nullable = false)
    @Builder.Default
    private LocalDate enrolledDate = LocalDate.now();

    @Column(name = "graduated_date")
    private LocalDate graduatedDate;

    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    // ── Parent / guardians ────────────────────────────────────────────────────

    @OneToMany(mappedBy = "student", cascade = CascadeType.ALL, orphanRemoval = true,
               fetch = FetchType.LAZY)
    @Builder.Default
    private List<StudentParent> parents = new ArrayList<>();

    // ── Helpers ───────────────────────────────────────────────────────────────

    public StudentParent getPrimaryParent() {
        return parents.stream()
                .filter(p -> p.isPrimary() && p.getDeletedAt() == null)
                .findFirst()
                .orElse(null);
    }
}
